name: google_maps_flutter_playground
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
  google_maps_flutter: ^2.11.0
  widget_to_marker: ^1.0.6
  geolocator: ^13.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/